### PR TITLE
CDE-66 Preview missing functionalities

### PR DESCRIPTION
**Pull request by Aiga115**
Issue #CDE-66
Problem: Preview missing functionalities
Solution: 
Fix chip ui misalignment, add icon functionality

https://github.com/MetaCell/cde-mapper/assets/67194168/6d3b30ae-f8b5-416e-b652-9abd2e33df98

### CODE REVIEW

**Review by afonsobspinto — CHANGES_REQUESTED** [review]
I still see the misalignment between chips and table:

image

**Comment by Aiga115** [comment]
> I still see the misalignment between chips and table:
> 
> image

Sorry @afonsobspinto I don't see any misalignment between table and chips, like even the parent box of each chip has fixed height

**Comment by afonsobspinto** [comment]
> Sorry @afonsobspinto I don't see any misalignment between table and chips, like even the parent box of each chip has fixed height

@Aiga115 I still see the misalignment. I'm adding @ddelpiano as reviewer to see what he experiences.

**Review by ddelpiano — CHANGES_REQUESTED** [review]
- change the text 'No mapping yet' to 'Header not mapped'
- make the chips part of the table, so just add a row on top where in each cell you place the chip, no border and white background, this should solve the entire alignment issue.

**Review by afonsobspinto — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
